######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 2 10:25:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Clock.h FisherClock.h MainWindow.h
SOURCES += Clock.cpp FisherClock.cpp main.cpp MainWindow.cpp
